site_name: simsity
repo_url: https://github.com/koaning/simsity
site_url: https://koaning.github.io/simsity/
site_description: Simsity is a Super Simple Similarities Service.
site_author: Vincent D. Warmerdam

nav:
  - Home: index.md
  - Getting Started:
    - Quickstart: quickstart/index.md
  - API:
    - simsity.service: api/service.md
    - simsity.indexer: api/indexer.md
    - simsity.datasets: api/datasets.md
    - simsity.preprocessing: api/preprocessing.md
plugins:
  - mkdocstrings
  - search
copyright: Maintained by <a href="https://twitter.com/fishnets88">Vincent</a>.
theme:
  name: material
  favicon: venn.png
  logo: venn.png
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
